[package]
name = "lctr"
version = "0.1.0"
authors = ["Jakub Matraszek <jakub.matraszek@gmail.com>"]

[dependencies.wiringpi]
# version = "0.2.4"
git = "https://github.com/Ogeon/rust-wiringpi.git"
features = ["orangepi"]
